# Generated by Django 5.1.5 on 2025-01-27 05:16

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_profile_school_school_created_at_school_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default=webapp.models.generate_slug),
        ),
    ]
