# Generated by Django 5.1.5 on 2025-01-27 05:16

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_school_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(default=webapp.models.generate_slug),
        ),
    ]
