# Generated by Django 5.1.5 on 2025-01-28 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.school'),
        ),
    ]
