# Generated by Django 5.1.5 on 2025-01-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_product_category_alter_product_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
