# Generated by Django 5.1.5 on 2025-01-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_categories_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
