# Generated by Django 5.1.5 on 2025-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
