# Generated by Django 5.1.5 on 2025-01-29 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_range', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_options', to='webapp.categories')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_options', to='webapp.school')),
            ],
            options={
                'unique_together': {('category', 'school')},
            },
        ),
    ]
