# Generated by Django 5.1.5 on 2025-01-29 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_product_stock_sizeoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='webapp.school'),
        ),
    ]
