# Generated by Django 5.1.5 on 2025-01-30 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_categories_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='webapp.categories')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='webapp.school')),
            ],
            options={
                'unique_together': {('category', 'school')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='webapp.size'),
        ),
        migrations.DeleteModel(
            name='SizeOption',
        ),
    ]
