# Generated by Django 5.1.5 on 2025-01-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_remove_product_size_size_product_sizes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('category',)},
        ),
        migrations.RemoveField(
            model_name='size',
            name='school',
        ),
    ]
